FormKey: 0742B2:Campfire.esm
EditorID: _Camp_legacyconfig_senseobjective_on
Description:
  TargetLanguage: English
  Value: >-
    Sense Objective


    If enabled, the path to your next quest objective will be briefly displayed when using Instincts.


    Current Setting: Enabled
INAM: 0x00000000
Flags:
- MessageBox
MenuButtons:
- Text:
    TargetLanguage: English
    Value: Disable
- Text:
    TargetLanguage: English
    Value: Back
