FormKey: 039AF9:Campfire.esm
EditorID: _Camp_legacyconfig_followersremovegear_on
Description:
  TargetLanguage: English
  Value: >-
    Remove Gear in Tents (Followers)


    If enabled, your followers will remove their worn weapons and shield, and place them in and around your tent when sitting or sleeping.


    Current Setting: Enabled
INAM: 0x00000000
Flags:
- MessageBox
MenuButtons:
- Text:
    TargetLanguage: English
    Value: Disable
- Text:
    TargetLanguage: English
    Value: Back
