FormKey: 035991:Campfire.esm
EditorID: _Camp_legacyconfig_showshield_off
Description:
  TargetLanguage: English
  Value: >-
    Show Shield in Tent


    If enabled, your worn shield will be removed from your character and placed in and around your tent when sitting or sleeping on your bed roll.


    Current Setting: Disabled
INAM: 0x00000000
Flags:
- MessageBox
MenuButtons:
- Text:
    TargetLanguage: English
    Value: Enable
- Text:
    TargetLanguage: English
    Value: Back
