// GENERATED by tools/gen_mcm_table.py from Campfire's own MCM script, Campfire.esm and English strings. Do not edit by hand.
// Campfire is by Chesko; its scripts and plugin are MIT licensed (the meshes and textures are not part of this).
#pragma once

#include <iterator>

namespace mcm
{
	enum class Kind { Header, Column, Toggle, Slider, Menu, Key };

	// One row of a page. formId is the local FormID of the setting's global in Campfire.esm (0 for headers and column breaks).
	// Toggles hold 1 (off) or 2 (on). A menu stores its list position plus menuBase. Key: def is the hotkey slot (0 create item, 1 build campfire,
	// 2 harvest wood, 3 instincts). gate: the row is greyed out unless this global is 2. special: 1 = follower tracking, 2 = Equipping Overhaul.
	struct Entry
	{
		Kind                kind;
		const char*         label;
		unsigned int        formId;
		const char*         profileKey;
		float               def, min, max, step;
		const char*         format;
		const char* const*  options;
		int                 optionCount;
		int                 menuBase;
		unsigned int        gate;
		int                 special;
		const char*         tip;
	};

	inline constexpr const char* kList_Gameplay_SettingCampingCampfireMode_OID[] = {
		"Quick",
		"Realistic",
	};

	struct Page
	{
		const char*  title;
		const Entry* entries;
		int          count;
	};

	inline constexpr Entry kEntries0[] = {
		{ Kind::Header, "Camping", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Menu, "Campfire Building", 0x075842, "campfire_mode", 1, 0, 0, 0, "", kList_Gameplay_SettingCampingCampfireMode_OID, 2, 0, 0, 0, "Quick: 4 firewood or deadwood is used, and the campfire is lit automatically.\\nRealistic: You must use tinder, starting fuel, and lighting the campfire takes skill and time.\\nDefault: Realistic" },
		{ Kind::Toggle, "Player Removes Gear in Tents", 0x03EA70, "tent_remove_player_equipment", 2, 0, 0, 0, "", nullptr, 0, 0, 0x000000, 0, "If enabled, you will remove certain pieces of gear when sitting or lying down inside a tent, and display those items inside. They are re-equipped when you get back up.\\nDefault: On" },
		{ Kind::Toggle, "Camping Illegal in Settled Areas", 0x02409E, "camping_illegal_in_towns", 2, 0, 0, 0, "", nullptr, 0, 0, 0x000000, 0, "If enabled, you will be unable to place camping equipment near cities or inside houses, inns, and other owned spaces. You can still place camping equipment in the wilderness and inside dungeons and caves.\\nDefault: On" },
		{ Kind::Toggle, "Camping Equipment Can Burn", 0x03A060, "camping_gear_flammable", 2, 0, 0, 0, "", nullptr, 0, 0, 0x000000, 0, "If enabled, certain pieces of camping equipment will be flammable, and can begin to burn when hit with a torch, flame spell, or shout. The fire can be put out with a frost spell before the item becomes consumed. If fire engulfs the item, it will be destroyed.\\nDefault: On" },
		{ Kind::Header, "Hotkeys", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Key, "Create Item", 0x035F12, "hotkey_create_item", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "Click to set a key to quickly use the Create Item ability.\\nThis will remove the Create Item power from your spell list. Default the hotkey to acquire the power again." },
		{ Kind::Key, "Build Campfire", 0x035F10, "hotkey_build_campfire", 1, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "Click to set a key to quickly use the Build Campfire ability.\\nThis will remove the Build Campfire power from your spell list. Default the hotkey to acquire the power again." },
		{ Kind::Key, "Harvest Wood", 0x035F11, "hotkey_harvest_wood", 2, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "Click to set a key to quickly use the Harvest Wood ability.\\nThis will remove the Harvest Wood power from your spell list. Default the hotkey to acquire the power again." },
		{ Kind::Key, "Instincts", 0x050B89, "hotkey_instincts", 3, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "Click to set a key to quickly use the Instincts ability.\\nThis will remove the Instincts power from your spell list. Default the hotkey to acquire the power again." },
		{ Kind::Column, "", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Header, "Player Tent Behavior", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Toggle, "Remove Armor / Clothing", 0x0250E2, "tent_remove_player_cuirass", 1, 0, 0, 0, "", nullptr, 0, 0, 0x03EA70, 0, "If enabled, you will remove your armor or clothing and place it inside your tent when you sit or lie down. It is re-equipped when you get back up.\\nDefault: On" },
		{ Kind::Toggle, "Remove Gauntlets / Gloves", 0x0250E3, "tent_remove_player_gauntlets", 2, 0, 0, 0, "", nullptr, 0, 0, 0x03EA70, 0, "If enabled, you will remove your gloves or gauntlets and place them inside your tent when you sit or lie down. They are re-equipped when you get back up.\\nDefault: On" },
		{ Kind::Toggle, "Remove Backpack", 0x0250E5, "tent_remove_player_backpack", 2, 0, 0, 0, "", nullptr, 0, 0, 0x03EA70, 0, "If enabled, you will remove your backpack and place it inside your tent when you sit or lie down. It is re-equipped when you get back up.\\nDefault: On" },
		{ Kind::Toggle, "Remove Weapons", 0x0250E6, "tent_remove_player_weapons", 2, 0, 0, 0, "", nullptr, 0, 0, 0x03EA70, 0, "If enabled, you will remove your weapons and place them inside your tent when you sit or lie down. They are re-equipped when you get back up.\\nDefault: On" },
		{ Kind::Toggle, "Remove Shield", 0x0250E7, "tent_remove_player_shield", 2, 0, 0, 0, "", nullptr, 0, 0, 0x03EA70, 0, "If enabled, you will remove your shield and place it near your tent when you sit or lie down. It is re-equipped when you get back up.\\nDefault: On" },
		{ Kind::Toggle, "Remove Ammo", 0x0250E8, "tent_remove_player_ammo", 2, 0, 0, 0, "", nullptr, 0, 0, 0x03EA70, 0, "If enabled, you will remove your quiver or crossbow bolts when you sit or lie down. They are re-equipped when you get back up.\\nNote: Ammo is not displayed in tents.\\nDefault: On" },
		{ Kind::Toggle, "Remove Helm / Head Gear (See Note)", 0x0250E1, "tent_remove_player_helm", 2, 0, 0, 0, "", nullptr, 0, 0, 0x03EA70, 0, "If enabled, you will remove your helm or head gear and place it inside your tent when you sit or lie down. It is re-equipped when you get back up.\\nNote: Self-enchanted head gear will not re-apply enchantment effects after getting out of a tent. This is a game engine issue. Disable if you use self-enchanted head gear.\\nDefault: On" },
		{ Kind::Toggle, "Remove Boots / Shoes (See Note)", 0x0250E4, "tent_remove_player_boots", 2, 0, 0, 0, "", nullptr, 0, 0, 0x03EA70, 0, "If enabled, you will remove your boots or shoes and place them inside your tent when you sit or lie down. They are re-equipped when you get back up.\\nNote: Self-enchanted foot gear will not re-apply enchantment effects after getting out of a tent. This is a game engine issue. Disable if you use self-enchanted foot gear.\\nDefault: On" },
		{ Kind::Header, "Follower Behavior", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Toggle, "Followers Interact with Campsite", 0x039AF5, "followers_use_campsite", 2, 0, 0, 0, "", nullptr, 0, 0, 0x035983, 0, "If enabled, your followers (up to 3) will sleep in spare bed rolls when you lay down, and sit inside a tent or near campfires when you do.\\nDefault: On" },
		{ Kind::Toggle, "Followers Remove Gear in Tents", 0x039AF6, "tent_remove_follower_equipment", 2, 0, 0, 0, "", nullptr, 0, 0, 0x035983, 0, "If enabled, your followers will remove their worn weapons and shield, and place them inside your tent when sitting or sleeping.\\nDefault: On" },
	};
	inline constexpr Entry kEntries1[] = {
		{ Kind::Header, "Detection", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Toggle, "Find Tinder Items", 0x06DC4B, "instincts_find_tinder", 2, 0, 0, 0, "", nullptr, 0, 0, 0x000000, 0, "If enabled, items that can be used as tinder for campfires will be detected with a yellow glow when using Instincts.\\nDefault: Enabled" },
		{ Kind::Toggle, "Find Flora", 0x06DC4C, "instincts_find_flora", 2, 0, 0, 0, "", nullptr, 0, 0, 0x000000, 0, "If enabled, general flora (plants, mushrooms, etc) will be detected with a blue glow when using Instincts. \\nDefault: Enabled" },
		{ Kind::Toggle, "Hear Creature Movement", 0x06DC4D, "instincts_hear_creatures", 2, 0, 0, 0, "", nullptr, 0, 0, 0x000000, 0, "If enabled, creatures that are moving or talking will emit sound waves that can be seen through walls when using Instincts. If close enough, you can detect creatures even when they aren't moving.\\nNote: Changes to this setting can take up to 15 seconds to apply!\\nDefault: Enabled" },
		{ Kind::Toggle, "Smell Dead", 0x06DC4E, "instincts_smell_dead", 2, 0, 0, 0, "", nullptr, 0, 0, 0x000000, 0, "If enabled, you will be able to smell dead bodies and the undead when using Instincts.\\nNote: Changes to this setting can take up to 15 seconds to apply!\\nDefault: Enabled" },
		{ Kind::Toggle, "Sense Path to Next Objective", 0x06DC4F, "instincts_sense_objective", 1, 0, 0, 0, "", nullptr, 0, 0, 0x000000, 0, "If enabled, the path to your next quest objective will be briefly displayed when using Instincts.\\nDefault: Disabled" },
		{ Kind::Header, "Effects", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Toggle, "Visual Distortion Effect", 0x06DC50, "instincts_vfx", 2, 0, 0, 0, "", nullptr, 0, 0, 0x000000, 0, "Toggle the visual distortion effect when starting Instincts on or off.\\nDefault: Enabled" },
		{ Kind::Toggle, "Sound Effect", 0x06DC51, "instincts_sfx", 2, 0, 0, 0, "", nullptr, 0, 0, 0x000000, 0, "Toggle the sound effect when starting Instincts on or off.\\nDefault: Enabled" },
	};
	inline constexpr Entry kEntries2[] = {
		{ Kind::Header, "Object Placement", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Toggle, "Advanced Object Placement", 0x048CEE, "advanced_placement_mode", 2, 0, 0, 0, "", nullptr, 0, 0, 0x000000, 0, "If enabled, the placement indicator will follow where you look and move, and snap to the slope of the terrain. This allows for very precise placement. If you are experiencing performance issues, try disabling this feature to place items in a simpler way (indicator doesn't follow movements or snap to terrain).\\nDefault: On" },
		{ Kind::Slider, "Max Placement Threads", 0x026EAF, "max_placement_threads", 20, 0, 30, 1, "{0}", nullptr, 0, 0, 0, 0, "When placing camping equipment, the system distributes the work across \"threads\" to place the object faster. This helps speed up placing complex objects, like tents. The system can use up to 30 threads. If you are experiencing undesired behavior when placing tents or other objects, try reducing the maximum number of threads.\\nDefault: 20" },
		{ Kind::Header, "Campfire System", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Toggle, "Track Followers", 0x035983, "follower_tracking", 2, 0, 0, 0, "", nullptr, 0, 0, 0x000000, 1, "If enabled, Campfire will track 3 of your nearest followers and your pet. This enables features like followers sleeping in the bed rolls of tents. If disabled, ALL follower features in Campfire AND ANY OTHER CAMPFIRE-BASED MOD will be disabled. Disabling this feature is not recommended.\\nIf you are affected by the \"brawl bug\", try temporarily disabling this feature.\\nDefault: On" },
		{ Kind::Header, "Compatibility", 0, "", 0, 0, 0, 0, "", nullptr, 0, 0, 0, 0, "" },
		{ Kind::Toggle, "Equipping Overhaul", 0x052C04, "eo_compatibility", 1, 0, 0, 0, "", nullptr, 0, 0, 0x000000, 2, "Enable or disable an Equipping Overhaul compatibility work-around.\\nDefault: Disabled" },
	};

	inline constexpr Page kPages[] = {
		{ "Gameplay", kEntries0, static_cast<int>(std::size(kEntries0)) },
		{ "Instincts", kEntries1, static_cast<int>(std::size(kEntries1)) },
		{ "Advanced", kEntries2, static_cast<int>(std::size(kEntries2)) },
	};
}
