"""Writes plugin/src/EslMap.h from esl-work/map_campfire.json (tools/esl_build.py): old local FormID -> ESL local FormID, which Campfire.dll uses
when Campfire.esm is loaded as a light plugin. The normal build never consults it.

Usage: python tools/gen_eslmap.py
"""
import json
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
mp = json.load(open(os.path.join(HERE, "esl-work", "map_campfire.json")))
rows = sorted((int(k, 16), int(v, 16)) for k, v in mp.items())
lines = [
    "// GENERATED by tools/gen_eslmap.py from esl-work/map_campfire.json. Old local FormID -> ESL local FormID, used when Campfire.esm is loaded as a light plugin.",
    "#pragma once",
    "",
    "namespace eslmap",
    "{",
    "\tstruct Pair { unsigned int from, to; };",
    "\tinline constexpr Pair kCampfire[] = {",
]
lines += [f"\t\t{{ 0x{a:06X}, 0x{b:06X} }}," for a, b in rows]
lines += ["\t};", "}", ""]
with open(os.path.join(HERE, "plugin", "src", "EslMap.h"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print(f"plugin/src/EslMap.h: {len(rows)} Campfire ids")
